name: Cache Node and NPM Dependencies
description: "This action allows to cache both Node and NPM dependencies based on the package-lock.json file."
inputs:
    node-version:
        description: "NodeJS version to use"
        required: true
        default: "24.x"
    working-dir:
        description: "The working directory of the application"
        required: false
        default: .
    target-env:
        required: false
        description: '"dev" or "prod". Controls whether dev dependencies are installed'
        default: dev
runs:
    using: "composite"
    steps:
        - name: "Setup NodeJS version ${{ inputs.node-version }}"
          uses: actions/setup-node@v6
          with:
              node-version: ${{ inputs.node-version }}
          
        - name: "Cache dependencies"
          id: cache
          uses: actions/cache@v6
          with:
              key: node-modules-${{inputs.target-env}}-${{ hashFiles(format('{0}/{1}', inputs.working-dir, 'package-lock.json')) }}
              path: ${{ inputs.working-dir }}/node_modules
        
        - name: Install dependencies
          if: ${{ steps.cache.outputs.cache-hit != 'true' }}
          shell: bash
          working-directory: ${{ inputs.working-dir }}
          run: |
            if [[ "${{ inputs.target-env }}" == "prod" ]]; then
              npm ci --omit=dev
            else
              npm ci
            fi
          